### ISSUE TITLE
set window title

### ISSUE THREAD

**Issue by gpatmore** [acaudwell/Logstalgia#9]
I tend to run several instances of logstalgia on my monitors while I work. One for each subsystem.  It would be super helpful if you could add a configuration param to set the window title... or add a title somewhere. 

Great project! I use this a whole lot to visualize all our nginx connected systems.

**Comment by mclang** [comment]
I'm also monitoring several servers, so this would be great addition.

**Comment by mclang** [comment]
I found that window title is set [here](https://github.com/acaudwell/Logstalgia/blob/4691998f3e6953ab04fbaa371ccf3551c7afbc21/src/main.cpp#L145)

If I want to try to add this improvement, to how many files and places I have to make changes? I'm asking some pointers because I may not have time to learn whole codebase, but I am willing to do something usefull.

**Comment by acaudwell** [comment]
I think my preferred approach would be to make the title on screen, maybe below the IP summarizer rather than in the window title, so you can also have a title if using a borderless window or full screen. 

logstalgia.cpp would need to change to draw the title and make the summarizer smaller. settings.cpp would need to be modified to add the new setting to control the title, and the documentation would need to be updated (README and data/logstalgia.1)

**Comment by mclang** [comment]
Okay, thanks.

I will see if I manage to do something. But don't hold your breath, life is busy nowadays.

**Comment by mclang** [comment]
And almost year later I have something.

I made a pull request with the changes. It does not yet include documentation changes because I thing there is improvements to be made. One of those is that I thing _windows title_ is wrong name - this doesn't set the windows title after all. Maybe it should be called _host name_ or something similar or maybe the real window title should be set also?

How does it look otherwise, @acaudwell ?

**Comment by acaudwell** [comment]
In the new version. Thanks
